version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building project..."
  post_build:
    commands:
      - echo "Build completed successfully!"
